language: python
python:
    - 3.6
notifications:
  email: false
addons:
  apt:
    packages:
    - mysql-server
    - mysql-client
sudo: false
before_install: "pip install -r requirements.txt"
install: "python setup.py develop"
script: "coverage run tests/*"


branches:
  only:
    - master
    - dev

