notifications:
	email: false

sudo: false
language: python
python:
    - 3.6
    
before_install: "pip install -r requirements.txt
install: "python setup.py develop"
script: true


branches:
  only:
    - master
    - dev

